info = {
    "main":{
        "ui":true
    },
    "ui":{
        "width":"1920px",
        "height":"1080px",
        "backgroundImage":"img/backgroundImage.png",
        "sidebar":{
            "width":"50px",
            "color":"white",
            "opacity":"0.4"
        },
        "icons":{
            "width":"1280px",
            "height":"720px",
            "top":"180px",
            "left":"330px"
        }
    },
    "password":"admin"
}