info = {
    "main":{
        "ui":true
    },
    "ui":{
        "width":"1920px",
        "height":"1080px",
        "backgroundImage":"img/backgroundImage.png",
        "sidebar":{
            "width":"50px",
            "color":"white",
            "opacity":"0.4"
        },
        "icons":{
            "width":"1280px",
            "height":"720px",
            "top":"180px",
            "left":"330px"
        }
    },
    "clock":{
        "top":"193px",
        "left":"330px",
        "backgroundColor":"white",
        "opacity":"0.7",
        "color":"blue"
    },
    "password":null,
    "version":[1,1,3]
}